name: Terraform

on:
  push:
    paths:
      - 'users/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        user-dir: [user1, user2]  # Add more directories as needed
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: terraform -chdir=users/${{ matrix.user-dir }} init

    - name: Terraform Plan
      run: terraform -chdir=users/${{ matrix.user-dir }} plan -var-file=${{ matrix.user-dir }}.tfvars

    - name: Terraform Apply
      run: terraform -chdir=users/${{ matrix.user-dir }} apply -var-file=${{ matrix.user-dir }}.tfvars -auto-approve

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve